name: Scrape Talk Locations

on:
  push:
    paths:
      - 'talks/**'
      - '_talks/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write           # This workflow pushes to the repository

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'   # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install getorg --upgrade
